// ast_calc_parser.bison.y

/*
MIT License

Copyright (c) 2024-2026 Zartaj Majeed

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

// bison -Wall -Wdangling-alias -Werror --color=always -Wcounterexamples --report=counterexamples,lookaheads --report-file=bisonreport.txt ast_calc_parser.bison.y

// c++ parser classes skeleton file
%skeleton "lalr1.cc"

%require "3.8"

// c++ parser
%language "c++"

// generate parser description report .output file
%verbose

/*
%defines "ast_calc_parser.bison.h"
%output "ast_calc_parser.bison.cpp"
*/

// enable debug trace
%define parse.trace

// adds location parameter to symbol constructors
%locations

// generate header for location to be used outside of bison parser
%define api.location.file "locations.bison.h"

%define parse.error detailed

// want to return character token from flex but don't think it can work with api.token.constructor
// better lookup performance at cost of disallowing literal characters in grammar
%define api.token.raw

%code requires {
// %code requires codeblock goes at top of .h outside of namespace and parser class
// standard c++ #includes and defines

/*
MIT License

Copyright (c) 2024-2026 Zartaj Majeed

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#include <stdint.h>

#include <string>
#include <vector>
#include <functional>
#include <chrono>
#include <unordered_map>
#include <print>

#include "locations.bison.h"

#include "ast/ast_calc_ast.h"

#ifdef _MSC_VER
// disable vc++ warning C4065, switch statement contains default but no case labels in code generated for basic_symbol::clear() in .h file
#pragma warning(push)
#pragma warning(disable: 4065)
#endif

namespace astcalc {

using namespace std;
using namespace chrono;

struct BisonParam {
  CalcAstNode ast;
  unordered_map<string, int64_t> symtab;
  struct Stats {
    time_point<steady_clock> parseStartTime;
    time_point<steady_clock> parseEndTime;
    duration<double> parseTimeSec;
  } stats{};
};

// info for lexer to use in yylex
struct LexParam {
// position in input stream for lexer to update
  location loc{};
};

}

// println formatter for location object
template<>
struct std::formatter<astcalc::location> {
  std::format_context::iterator format(const astcalc::location& loc, std::format_context& ctx) const {
    std::ostringstream os;
    os << loc;
    return std::format_to(ctx.out(), "{}", os.str());
  }

  constexpr std::format_parse_context::const_iterator parse(std::format_parse_context& ctx) const {
    return ctx.begin();
  }
};

}

// custom namespace generated by bison
%define api.namespace {astcalc}

// custom classname generated by bison
%define api.parser.class {AstCalcParser}

// parser constructor parameter 1
// this is the yylex bison will call, it can have any signature we want since it's a lambda passed in by the client that wraps and hides the actual yylex call
%parse-param {function<AstCalcParser::symbol_type(LexParam&)> yylex}

// parser constructor parameter 2
%parse-param {BisonParam& bisonParam}

// parser constructor parameter 3
// only because each lex-param also must be parse-param
%parse-param {LexParam& lexParam}

// yylex parameter 1
// pass location and lexical feedback info to lexer
%lex-param {LexParam& lexParam}

// use actual types for tokens
%define api.value.type variant

// use c++ objects, changes signature of yylex, yylex now returns PGNParser::symbol_type, yylex takes no parameters, change everywhere yylex is referenced, eg parse-param, any lambdas
%define api.token.constructor

%define parse.assert

%code provides {
// %code provides codeblock
// goes in .h after namespace and parser class
// everything here needs AstCalcParser defined earlier

#ifdef _MSC_VER
#pragma warning(pop)
#endif

// parser objects
namespace astcalc {

using namespace std;

}

}

%code top {
// % code top
// appears as topmost code block in generated .cpp file just below gnu license
// your license for .cpp file

/*
MIT License

Copyright (c) 2024-2026 Zartaj Majeed

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

}

%{
// %{ unnamed codeblock
// goes at top of .cpp file after %code top, before namespace and parser class

%}

%code {
// %code
// appears in generated .cpp file after #include of generated .h file and before parser namespace and class

#include <string>
#include <vector>
#include <set>
#include <map>
#include <utility>
#include <algorithm>
#include <chrono>
#include <print>
#include <ranges>
#include <sstream>

#ifdef _MSC_VER
// disable vc++ warning C4065, switch statement contains default but no other case labels when there are no semantic actions
#pragma warning(push)
#pragma warning(disable: 4065)

// disable vc++ warning C4244, return conversion from const short to findqparser::FindqParser::state_type, possible loss of data 
#pragma warning(push)
#pragma warning(disable: 4244)
#endif

using namespace std;
using views::as_rvalue;

namespace {
  const auto defaultInputName = "inputstream"s;
}

void astcalc::AstCalcParser::error(const location& loc, const string& msg) {
  println("error at {}: {}", loc, msg);
}

}

%initial-action {
// %initial-action codeblock
// goes inside parse() function in .cpp, it's a separate brace-scoped block, anything declared here is local to this block and cannot be used anywhere else in parse()

// suppress unused variable warning till fix in release after version 3.8.2, https://github.com/akimd/bison/commit/a166d5450e3f47587b98f6005f9f5627dbe21a5b
// yynerrs_ is local to generated parse function
  (void)yynerrs_;

  bisonParam.stats.parseStartTime = steady_clock::now();

  auto& loc = lexParam.loc;

  if(loc.begin.filename == nullptr) {
    loc.initialize(&defaultInputName);
  }
}

%token DIV                      "/"
%token EQUAL                    "="
%token LEFT_PAREN               "("
%token MINUS                    "-"
%token PLUS                     "+"
%token RIGHT_PAREN              ")"
%token SEMICOLON                ";"
%token TIMES                    "*"

%token <string>                 IDENT
%token <int64_t>                INT

%nterm <AddExpr>                add_expr
%nterm <AssignExpr>             assign_expr
%nterm <vector<AssignExpr>>     assign_exprs
%nterm <Atom>                   atom
%nterm <Expr>                   expr
%nterm <Factor>                 factor
%nterm <Term>                   term

%start expr

%%

// no code allowed in rules section, just bison comments that are dropped from .cpp

expr:

  assign_exprs postprocess {

  println("bison.expr.1:");
  $$.assigns = move($assign_exprs);
  bisonParam.ast = $$;
}

| assign_exprs ";" postprocess {

  println("bison.expr.2:");
  $$.assigns = move($assign_exprs);
  bisonParam.ast = $$;
}

// right-recursive for right associative assignment
assign_exprs:

  assign_expr {

  println("bison.assign_exprs.1:");
  $$.push_back(move($assign_expr));
}

| assign_exprs ";" assign_expr {

  println("bison.assign_exprs.2:");
  $$ = move($1);
  $$.push_back(move($assign_expr));
}

assign_expr:

  IDENT "=" assign_expr[rhs] {

  println("bison.assign_expr.1:");
  if(!bisonParam.symtab.contains($IDENT)) {
    bisonParam.symtab[$IDENT] = 0;
  }
  $$ = Assignment{$IDENT, indirect<AssignExpr>{move($rhs)}};
}

| add_expr {

  println("bison.assign_expr.2:");
  $$ = move($add_expr);
}

add_expr:

  term {

  println("bison.add_expr.1:");
  $$.terms.push_back(move($term));
}

| add_expr "+" term {

  println("bison.add_expr.2:");
  $$ = move($1);
  $$.terms.push_back(move($term));
  $$.ops.push_back(AddExpr::op::plus);
}

| add_expr "-" term {

  println("bison.add_expr.3:");
  $$ = move($1);
  $$.terms.push_back(move($term));
  $$.ops.push_back(AddExpr::op::minus);
}

term:

  factor {

  println("bison.term.1:");
  $$.factors.push_back(move($factor));
}

| term "*" factor {

  println("bison.term.2:");
  $$ = move($1);
  $$.factors.push_back(move($factor));
  $$.ops.push_back(Term::op::times);
}

| term "/" factor {

  println("bison.term.3:");
  $$ = move($1);
  $$.factors.push_back(move($factor));
  $$.ops.push_back(Term::op::div);
}

factor:

  atom {

  println("bison.factor.1:");
  $$ = {$atom, Factor::op::none};
}

| "+" atom {

  println("bison.factor.2:");
  $$ = {$atom, Factor::op::plus};
}

| "-" atom {

  println("bison.factor.3:");
  $$ = {$atom, Factor::op::minus};
}

atom:

  INT {
  println("bison.atom.1:");
  $$ = $INT;
}

| IDENT {

  println("bison.atom.2:");
  if(!bisonParam.symtab.contains($IDENT)) {
    bisonParam.symtab[$IDENT] = 0;
  }
  $$ = move($IDENT);
}

| "(" expr ")" {

  println("bison.atom.3:");
  $$ = Group{$expr};
}

// midrule action for postprocessing
postprocess: %empty {
  auto& [start, end, elapsed] = bisonParam.stats;
  end = steady_clock::now();
  elapsed = end - start;
}

%%
// %code epilog block
// goes at bottom of generated .cpp file after namespace and parser implementation


#ifdef _MSC_VER
#pragma warning(pop)
#pragma warning(pop)
#endif

